### ISSUE TITLE
CF UAM bypass faild

### ISSUE THREAD

**Issue by ermya** [R00tS3c/Layer7-MultiBypass#7]
I think cloudflare UAM has been changed, and your bypass method dose not work right now

**Comment by andress134** [comment]
> I think cloudflare UAM has been changed, and your bypass method dose not work right now

The script is patched.
It uses several libraries that are outpdated
Cloudflare and the rest of the companies (ddg, sucuri, blazingfast etc) have made a lot of changes
This script cannot bypass anything

I recommend that you write your own repo script that is updated.
Or if you have no knowledge and are interested I can edit this script so that it can bypass the latest cloudflare update - ddg - sucuri.
Of course, if you are willing to pay for such a thing

**Comment by ermya** [comment]
Unfortunately I do not have enough mastery of JavaScript and I can not bypass cloudflare, There are a number of other ways, such as setting up a proxy server with a headless browser, just to bypass cloudlfare and receive a cookie. But the work is not neat! 
im looking for something like this script to at least bypass cloudflare UAM, and of course i will pay to save my time

**Comment by andress134** [comment]
> Unfortunately I do not have enough mastery of JavaScript and I can not bypass cloudflare, There are a number of other ways, such as setting up a proxy server with a headless browser, just to bypass cloudlfare and receive a cookie. But the work is not neat!
> im looking for something like this script to at least bypass cloudflare UAM, and of course i will pay to save my time

If you are willing to pay, you can contact me on discord for more information

JSFuncks#6323
